package edu.mlm.ecommercestore.config;

import edu.mlm.ecommercestore.entity.Category;
import edu.mlm.ecommercestore.entity.Product;
import edu.mlm.ecommercestore.entity.Role;
import edu.mlm.ecommercestore.entity.User;
import edu.mlm.ecommercestore.repository.CategoryRepository;
import edu.mlm.ecommercestore.repository.ProductRepository;
import edu.mlm.ecommercestore.repository.RoleRepository;
import edu.mlm.ecommercestore.repository.UserRepository;
import jakarta.transaction.Transactional;
import lombok.RequiredArgsConstructor;
import lombok.val;
import org.springframework.boot.CommandLineRunner;
import org.springframework.context.annotation.Configuration;
import org.springframework.security.crypto.password.PasswordEncoder;

import java.time.LocalDateTime;
import java.math.BigDecimal;
import java.util.Set;
import java.util.concurrent.ThreadLocalRandom;

/**
 * Initializes the database with default roles, users, and categories upon application startup.
 * <p>
 * This configuration class implements Spring Boot's {@link CommandLineRunner} to execute initial
 * data loading operations. It checks if the roles, categories and products are already populated in the database
 * and, if not, inserts default values. It also creates default admin and customer users with encoded
 * passwords for initial access to the system.
 * <p>
 * This setup ensures that the application is ready to be used right after startup, with essential
 * data structures and entries in place.
 */
@Configuration
@RequiredArgsConstructor
@Transactional
public class SQLRunner implements CommandLineRunner {

    private final UserRepository userRepository;
    private final RoleRepository roleRepository;
    private final PasswordEncoder passwordEncoder;
    private final CategoryRepository categoryRepository;
    private final ProductRepository productRepository;
    /**
     * Executes the initial data loading logic.
     * <p>
     * Checks the presence of roles, categories and products in their respective repositories and populates
     * them if they are found to be empty. It also ensures the creation of default admin and customer
     * user accounts.
     *
     * @param args command line arguments passed during application startup, not used in this implementation
     * @throws Exception if an error occurs during data initialization
     */
    @Transactional
    @Override
    public void run(String... args) throws Exception {
        // Roles initialization
        if (roleRepository.count() == 0) {
            val adminRole = roleRepository.save(new Role(1L, "ROLE_ADMIN"));
            val customerRole = roleRepository.save(new Role(2L, "ROLE_CUSTOMER"));
            // Default users creation
            userRepository.save(
                    new User(
                            1L,
                            "admin",
                            "admin@admin.com",
                            passwordEncoder.encode("Pass0rd1!"),
                            "https://i.pravatar.cc/300",
                            Set.of(adminRole)
                    )
            );
            userRepository.save(
                    new User(
                            2L,
                            "customer",
                            "customer@customer.com",
                            passwordEncoder.encode("Pass0rd1!"),
                            "https://i.pravatar.cc/300",
                            Set.of(customerRole)
                    )
            );
        }

        // Categories initialization
        if (categoryRepository.count() == 0) {
            categoryRepository.save(new Category(1L, "Laptop"));
            categoryRepository.save(new Category(2L, "Cellular"));
            categoryRepository.save(new Category(3L, "TV"));
            categoryRepository.save(new Category(4L, "Headphone"));
        }

        // Products initialization
        if (productRepository.count() == 0) {
            // Cellular Products
            productRepository.save(new Product(getRandomId(), "Samsung Galaxy S21", "Samsung", new BigDecimal("799.99"), "https://shop.samsung.com/ie/images/products/27522/14672/2000x2000/SM-G991BZADEUA.webp", "The Samsung Galaxy S21 specs are top-notch including a Snapdragon 888 chipset, 5G capability, 8GB RAM coupled with 128/256GB storage, and a 4000mAh battery. The phone sports a 6.2-inch Dynamic AMOLED display with an adaptive 120Hz refresh rate. In the camera department, a triple-sensor setup is presented.", "128GB", "6.2\"", "4000mAh", "Android", "Phantom Gray", categoryRepository.findById(2L).orElse(null), null, 0.0, LocalDateTime.now(), LocalDateTime.now()));
            productRepository.save(new Product(getRandomId(), "iPhone 12", "Apple", new BigDecimal("999.99"), "https://ik.imagekit.io/3dqckpw4d/upload/iphone_12___Black1657182277iphone-12-black.png", "The Apple iPhone 12 128GB in black is the perfect device for anyone looking for an amazing user experience. The iPhone 12 offers an amazing display, a powerful processor, and a large internal memory of 64GB. All of this in a stunning black design. The iPhone 12 comes with an excellent camera and advanced technologies like Face ID and 5G. These features promise you an amazing user experience and provide the perfect device for daily use.", "64GB", "6.1\"", "2815mAh", "iOS", "Black", categoryRepository.findById(2L).orElse(null), null, 0.0, LocalDateTime.now(), LocalDateTime.now()));
            productRepository.save(new Product(getRandomId(), "Google Pixel 5", "Google", new BigDecimal("699.99"), "https://caseface.ie/wp-content/uploads/Google-Pixel-5-Silicone-Case-Black.png", "There are a dual-camera setup and a fingerprint on the back. A 6-inch OLED display with a 90Hz refresh rate and 8MP selfie camera are presented at the front. Google Pixel 5 is powered by a 4080mAh battery and Android 11.", "128GB", "6.0\"", "4080mAh", "Android", "Black", categoryRepository.findById(2L).orElse(null), null, 0.0, LocalDateTime.now(), LocalDateTime.now()));
            productRepository.save(new Product(getRandomId(), "OnePlus 8T", "OnePlus", new BigDecimal("749.99"), "https://oasis.opstatics.com/content/dam/oasis/default/product-specs/8t-green.png", "The OnePlus 8T in Aquamarine Green seamlessly blends a classic Jade motif with a precision crafted glass finish. The Lunar Silver color showcases a captivating matte AG texture that's easy to grip and impossible to let go of.", "256GB", "6.55\"", "4500mAh", "Android", "Aquamarine Green", categoryRepository.findById(2L).orElse(null), null, 0.0, LocalDateTime.now(), LocalDateTime.now()));
            productRepository.save(new Product(getRandomId(), "Huawei P40 Pro", "Huawei", new BigDecimal("899.99"), "https://consumer.huawei.com/content/dam/huawei-cbg-site/common/mkt/list-image/phones/p40-pro/p40-pro-silver.png", "Huawei P40 Pro, a powerful variant in the P40 series, offers 5G and the Kirin 990 processor. It features a 6.58-inch OLED screen with 1200 x 2640 resolution and a 90Hz refresh rate. With 8GB RAM and 256GB storage (expandable via NM cards), it shines with its rear quad camera (50 MP, 40 MP, 12 MP periscope, TOF 3D) and dual front camera (32 MP + TOF 3D IR for depth and face recognition). The 4200 mAh battery supports wireless and fast charging, and it includes an in-screen fingerprint reader and HiFi sound.", "256GB", "6.58\"", "4200mAh", "Android", "Silver Frost", categoryRepository.findById(2L).orElse(null), null, 0.0, LocalDateTime.now(), LocalDateTime.now()));
            productRepository.save(new Product(getRandomId(), "Xiaomi Mi 11", "Xiaomi", new BigDecimal("799.99"), "https://media.power-cdn.net/images/h-db2787c3eaf510a6e35b88bdd4374f70/products/1164003/1164003_10_600x600_t_g.webp", "The Xiaomi Mi 11 is a flagship smartphone equipped with the powerful Snapdragon 888 processor, offering top-notch performance and features. It boasts a stunning 6.81-inch display and a robust 4600mAh battery. Available in Horizon Blue.", "128GB", "6.81\"", "4600mAh", "Android", "Horizon Blue", categoryRepository.findById(2L).orElse(null), null, 0.0, LocalDateTime.now(), LocalDateTime.now()));
            productRepository.save(new Product(getRandomId(), "Samsung Galaxy Note 20", "Samsung", new BigDecimal("999.99"), "https://static.doji.co/product/medias/smartphones/samsung/galaxy-note20/1-front-back-mystic-bronze.png", "The Samsung Galaxy Note 20 is a high-end smartphone featuring the iconic S Pen for productivity. It offers a 6.7-inch display, 256GB storage, and a 4300mAh battery. Available in Mystic Bronze.", "256GB", "6.7\"", "4300mAh", "Android", "Mystic Bronze", categoryRepository.findById(2L).orElse(null), null, 0.0, LocalDateTime.now(), LocalDateTime.now()));
            productRepository.save(new Product(getRandomId(), "iPhone 12 Mini", "Apple", new BigDecimal("699.99"), "https://assets.swappie.com/cdn-cgi/image/width=600,height=600,fit=contain,format=auto/swappie-iphone-12-mini-white.png?v=9166c13e", "The iPhone 12 Mini is a compact version of the iPhone 12, offering powerful performance in a smaller form factor. It features a 5.4-inch display, 64GB storage, and a 2227mAh battery. Available in White.", "64GB", "5.4\"", "2227mAh", "iOS", "White", categoryRepository.findById(2L).orElse(null), null, 0.0, LocalDateTime.now(), LocalDateTime.now()));
            productRepository.save(new Product(getRandomId(), "Google Pixel 4a", "Google", new BigDecimal("349.99"), "https://static.doji.co/product/medias/smartphones/google/pixel-4a/1-front_back-just-black.png", "The Google Pixel 4a is an affordable smartphone with an exceptional camera. It features a 5.81-inch display, 128GB storage, and a 3140mAh battery. Available in Just Black.", "128GB", "5.81\"", "3140mAh", "Android", "Black", categoryRepository.findById(2L).orElse(null), null, 0.0, LocalDateTime.now(), LocalDateTime.now()));
            productRepository.save(new Product(getRandomId(), "OnePlus Nord", "OnePlus", new BigDecimal("499.99"), "https://media-ik.croma.com/prod/https://media.croma.com/image/upload/v1708664240/Croma%20Assets/Communication/Mobiles/Images/262648_0_nwexmr.png?tr=w-600", "The OnePlus Nord is a mid-range smartphone with impressive features, including a 6.44-inch display, 128GB storage, and a 4115mAh battery. Available in Blue Marble.", "128GB", "6.44\"", "4115mAh", "Android", "Blue Marble", categoryRepository.findById(2L).orElse(null), null, 0.0, LocalDateTime.now(), LocalDateTime.now()));
            productRepository.save(new Product(getRandomId(), "Huawei Mate 40 Pro", "Huawei", new BigDecimal("1099.99"), "https://static.orangeromania.ro/webshop-images/hds_hwi0102101/huawei_huawei_mate_40_pro_5g_256gb_dual_sim_mystic_silver_l59456_7.png", "The Huawei Mate 40 Pro is a high-end smartphone with a powerful camera system. It features a 6.76-inch display, 256GB storage, and a 4400mAh battery. Available in Mystic Silver.", "256GB", "6.76\"", "4400mAh", "Android", "Mystic Silver", categoryRepository.findById(2L).orElse(null), null, 0.0, LocalDateTime.now(), LocalDateTime.now()));
            productRepository.save(new Product(getRandomId(), "Xiaomi Poco X3", "Xiaomi", new BigDecimal("229.99"), "https://static.doji.co/product/medias/smartphones/xiaomi/poco-x3-nfc/1-front-back-cobalt-blue.png", "The Xiaomi Poco X3 is a budget-friendly smartphone with good performance, featuring a 6.67-inch display, 128GB storage, and a 5160mAh battery. Available in Cobalt Blue.", "128GB", "6.67\"", "5160mAh", "Android", "Cobalt Blue", categoryRepository.findById(2L).orElse(null), null, 0.0, LocalDateTime.now(), LocalDateTime.now()));
            productRepository.save(new Product(getRandomId(), "Samsung Galaxy A52", "Samsung", new BigDecimal("499.99"), "https://fundamental.in/wp-content/uploads/2021/04/in-galaxy-a32-a325-sm-a325flvhins-409474890-600x480.png", "The Samsung Galaxy A52 is a mid-range smartphone with a vibrant AMOLED display. It features a 6.5-inch display, 128GB storage, and a 4500mAh battery. Available in Awesome Black.", "128GB", "6.5\"", "4500mAh", "Android", "Black", categoryRepository.findById(2L).orElse(null), null, 0.0, LocalDateTime.now(), LocalDateTime.now()));
            productRepository.save(new Product(getRandomId(), "iPhone SE (2020)", "Apple", new BigDecimal("399.99"), "https://i0.wp.com/simfreephone.co.il/wp-content/uploads/2023/05/iphone-se-2020-buyiphone.co_.il-%D7%90%D7%93%D7%95%D7%9D.webp", "The iPhone SE (2020) is a compact smartphone with powerful performance. It features a 4.7-inch display, 64GB storage, and an 1821mAh battery. Available in Red.", "64GB", "4.7\"", "1821mAh", "iOS", "Red", categoryRepository.findById(2L).orElse(null), null, 0.0, LocalDateTime.now(), LocalDateTime.now()));
            productRepository.save(new Product(getRandomId(), "Google Pixel 4 XL", "Google", new BigDecimal("899.99"), "https://static.doji.co/product/medias/smartphones/google/pixel-4-xl/1-front-back-clearly-white.png", "The Google Pixel 4 XL is a large-screen smartphone with excellent camera capabilities. It features a 6.3-inch display, 128GB storage, and a 3700mAh battery. Available in Clearly White.", "128GB", "6.3\"", "3700mAh", "Android", "White", categoryRepository.findById(2L).orElse(null), null, 0.0, LocalDateTime.now(), LocalDateTime.now()));
            productRepository.save(new Product(getRandomId(), "OnePlus 7T", "OnePlus", new BigDecimal("599.99"), "https://cdn.revendo.com/media/04/fb/7c/1662392043/oneplus-7t-frosted-silver-guenstig-gebraucht-kaufen.png.png", "The OnePlus 7T is a high-performance smartphone featuring a 90Hz display for smooth visuals. It has a 6.55-inch display, 128GB storage, and a 3800mAh battery. Available in Frosted Silver.", "128GB", "6.55\"", "3800mAh", "Android", "Frosted Silver", categoryRepository.findById(2L).orElse(null), null, 0.0, LocalDateTime.now(), LocalDateTime.now()));
            productRepository.save(new Product(getRandomId(), "Huawei Nova 7i", "Huawei", new BigDecimal("299.99"), "https://netcomcellular.com/home/wp-content/uploads/2020/06/Huawei-Nova-7i.png", "The Huawei Nova 7i is an affordable smartphone with good performance and features. It has a 6.4-inch display, 128GB storage, and a 4200mAh battery. Available in Crush Green.", "128GB", "6.4\"", "4200mAh", "Android", "Crush Green", categoryRepository.findById(2L).orElse(null), null, 0.0, LocalDateTime.now(), LocalDateTime.now()));
            productRepository.save(new Product(getRandomId(), "Xiaomi Redmi Note 10", "Xiaomi", new BigDecimal("199.99"), "https://mobelix.com.mk/storage/app/uploads/public/606/c26/58d/thumb_2657_800_800_0_0_crop.png", "The Xiaomi Redmi Note 10 is a budget-friendly smartphone with an AMOLED display. It features a 6.43-inch display, 64GB storage, and a 5000mAh battery. Available in Shadow Black.", "64GB", "6.43\"", "5000mAh", "Android", "Black", categoryRepository.findById(2L).orElse(null), null, 0.0, LocalDateTime.now(), LocalDateTime.now()));
            productRepository.save(new Product(getRandomId(), "Samsung Galaxy S20 FE", "Samsung", new BigDecimal("699.99"), "https://images.samsung.com/is/image/samsung/p6pim/au/sm-g781bzbpxsa/gallery/au-galaxy-s20-fe-5g-g781-sm-g781bzbpxsa-530555372?$650_519_PNG$", "The Samsung Galaxy S20 FE is an affordable version of the Galaxy S20, offering similar features at a lower price. It has a 6.5-inch display, 128GB storage, and a 4500mAh battery. Available in Cloud Navy.", "128GB", "6.5\"", "4500mAh", "Android", "Cloud Navy", categoryRepository.findById(2L).orElse(null), null, 0.0, LocalDateTime.now(), LocalDateTime.now()));
            productRepository.save(new Product(getRandomId(), "iPhone 11", "Apple", new BigDecimal("799.99"), "https://static.doji.co/product/medias/smartphones/apple/iphone-11/1-front-back-green.png", "The iPhone 11 is a previous generation smartphone from Apple, known for its great features and performance. It has a 6.1-inch display, 64GB storage, and a 3110mAh battery. Available in Green.", "64GB", "6.1\"", "3110mAh", "iOS", "Green", categoryRepository.findById(2L).orElse(null), null, 0.0, LocalDateTime.now(), LocalDateTime.now()));
            productRepository.save(new Product(getRandomId(), "Google Pixel 3a", "Google", new BigDecimal("399.99"), "https://static.doji.co/product/medias/smartphones/google/pixel-3a/1-front-back-purple-ish.png", "The Google Pixel 3a is an affordable smartphone with an exceptional camera. It features a 5.6-inch display, 64GB storage, and a 3000mAh battery. Available in Purple-ish.", "64GB", "5.6\"", "3000mAh", "Android", "Purple", categoryRepository.findById(2L).orElse(null), null, 0.0, LocalDateTime.now(), LocalDateTime.now()));
            productRepository.save(new Product(getRandomId(), "OnePlus Nord N10", "OnePlus", new BigDecimal("299.99"), "https://topcellular.co.il/wp-content/uploads/2021/03/1-m00-1c-02-rb8bwl-samuay6slaakadlpvpzu488_840_840.png", "The OnePlus Nord N10 is a budget-friendly smartphone with 5G support. It features a 6.49-inch display, 128GB storage, and a 4300mAh battery. Available in Midnight Ice.", "128GB", "6.49\"", "4300mAh", "Android", "Midnight Ice", categoryRepository.findById(2L).orElse(null), null, 0.0, LocalDateTime.now(), LocalDateTime.now()));
            productRepository.save(new Product(getRandomId(), "Huawei Y9a", "Huawei", new BigDecimal("299.99"), "https://infinityza.co.za/wp-content/uploads/2022/07/Huawei-nova-Y9a-space-silver.png", "The Huawei Y9a is an affordable smartphone featuring a pop-up camera. It has a 6.63-inch display, 128GB storage, and a 4200mAh battery. Available in Space Silver.", "128GB", "6.63\"", "4200mAh", "Android", "Space Silver", categoryRepository.findById(2L).orElse(null), null, 0.0, LocalDateTime.now(), LocalDateTime.now()));
            productRepository.save(new Product(getRandomId(), "Xiaomi Mi 10T", "Xiaomi", new BigDecimal("499.99"), "https://fundamental.in/wp-content/uploads/2021/01/A306648A-FA43-45A5-12B7-7F7FE260A921.png", "The Xiaomi Mi 10T is a high-performance smartphone featuring a 144Hz display for smooth visuals. It has a 6.67-inch display, 128GB storage, and a 5000mAh battery. Available in Cosmic Black.", "128GB", "6.67\"", "5000mAh", "Android", "Black", categoryRepository.findById(2L).orElse(null), null, 0.0, LocalDateTime.now(), LocalDateTime.now()));

            // TV Products
            productRepository.save(new Product(getRandomId(), "Samsung QLED 4K TV", "Samsung", new BigDecimal("1199.99"), "https://images.samsung.com/is/image/samsung/il-qledtv-q70t-qe65q70tatxsq-frontblack-253960988?$650_519_PNG$", "The Samsung QLED 4K TV offers a stunning QLED display with 4K resolution, delivering vibrant colors and deep blacks. Perfect for a cinematic viewing experience in the comfort of your home. Available in Black.", null, "55\"", null, "Tizen", "Black", categoryRepository.findById(3L).orElse(null), null, 0.0, LocalDateTime.now(), LocalDateTime.now()));
            productRepository.save(new Product(getRandomId(), "LG OLED TV", "LG", new BigDecimal("1499.99"), "https://www.sathya.store/img/product/JWf0I3UAg5fTa0GC.png", "The LG OLED TV features a beautiful OLED display, known for perfect blacks and vivid colors. With its sleek design and exceptional picture quality, it's ideal for movie lovers and gamers. Available in Black.", null, "65\"", null, "WebOS", "Black", categoryRepository.findById(3L).orElse(null), null, 0.0, LocalDateTime.now(), LocalDateTime.now()));
            productRepository.save(new Product(getRandomId(), "Sony Bravia 4K", "Sony", new BigDecimal("1299.99"), "https://images.webfronts.com/cache/frbrrqxngnrs.dat", "The Sony Bravia 4K TV offers stunning clarity with its 4K HDR display, providing an immersive viewing experience. It's powered by Android TV, giving access to numerous apps and streaming services. Available in Silver.", null, "55\"", null, "Android TV", "Silver", categoryRepository.findById(3L).orElse(null), null, 0.0, LocalDateTime.now(), LocalDateTime.now()));
            productRepository.save(new Product(getRandomId(), "Samsung Q80T", "Samsung", new BigDecimal("1199.99"), "https://www.samline.co.il/wp-content/uploads/2021/03/Q80TQTD2_003_L-Perspective_Carbon-Silver-2-795x530.png", "The Samsung Q80T is a premium 4K TV with stunning picture quality, featuring Quantum HDR 12X, Object Tracking Sound, and Ambient Mode+. It runs on Samsung's Tizen OS, offering a seamless smart TV experience. Available in Silver.", null, "65\"", null, "Tizen OS", "Silver", categoryRepository.findById(3L).orElse(null), null, 0.0, LocalDateTime.now(), LocalDateTime.now()));
            productRepository.save(new Product(getRandomId(), "Vizio M-Series", "Vizio", new BigDecimal("599.99"), "https://www.vizio.com/content/dam/vizio/2021/qr/tv/m-series/m/mobile/3/TV.png", "The Vizio M-Series offers great value as a mid-range 4K TV, featuring Quantum Color and Dolby Vision HDR. It's perfect for everyday viewing with SmartCast for easy streaming. Available in Black.", null, "50\"", null, "SmartCast", "Black", categoryRepository.findById(3L).orElse(null), null, 0.0, LocalDateTime.now(), LocalDateTime.now()));
            productRepository.save(new Product(getRandomId(), "LG CX Series", "LG", new BigDecimal("1499.99"), "https://hdtvtest.co.uk/static_data/content/fee_786_587_-33e7b21f-f66c-4145-acae-9a1a69f80fae.jpg", "The LG CX Series is a top-tier 4K OLED TV with exceptional picture quality, featuring Dolby Vision IQ, Dolby Atmos, and NVIDIA G-SYNC compatibility. It runs on LG's webOS, providing a rich smart TV experience. Available in Black.", null, "65\"", null, "WebOS", "Black", categoryRepository.findById(3L).orElse(null), null, 0.0, LocalDateTime.now(), LocalDateTime.now()));
            productRepository.save(new Product(getRandomId(), "Hisense H8G", "Hisense", new BigDecimal("599.99"), "https://hisense.com.au/wp-content/uploads/2024/04/Q6-Filter-Page-Image-72dpi-1580x1176px.png", "The Hisense H8G offers great performance for a budget 4K TV, featuring Dolby Vision HDR and full array local dimming. It's powered by Android TV for a wide range of apps and services. Available in Black.", null, "55\"", null, "Android TV", "Black", categoryRepository.findById(3L).orElse(null), null, 0.0, LocalDateTime.now(), LocalDateTime.now()));
            productRepository.save(new Product(getRandomId(), "Samsung The Frame", "Samsung", new BigDecimal("1299.99"), "https://images.samsung.com/is/image/samsung/p6pim/il/qe43ls03bauxsq/gallery/il-the-frame-ls03b-qe43ls03bauxsq-532311004?$650_519_PNG$", "Samsung The Frame is a stylish TV that doubles as artwork when not in use. It features a customizable frame and QLED 4K display, blending seamlessly into your home decor. Available in Black.", null, "55\"", null, "Tizen", "Black", categoryRepository.findById(3L).orElse(null), null, 0.0, LocalDateTime.now(), LocalDateTime.now()));
            productRepository.save(new Product(getRandomId(), "LG NanoCell TV", "LG", new BigDecimal("999.99"), "https://varibuy.com/wp-content/uploads/2023/05/LG-75NANO95VPA.png.webp", "The LG NanoCell TV offers advanced NanoCell technology for enhanced color accuracy and 4K resolution. It's perfect for sports and movies, powered by WebOS for seamless streaming. Available in Black.", null, "65\"", null, "WebOS", "Black", categoryRepository.findById(3L).orElse(null), null, 0.0, LocalDateTime.now(), LocalDateTime.now()));
            productRepository.save(new Product(getRandomId(), "Sony X950H", "Sony", new BigDecimal("1399.99"), "https://cdn.vox-cdn.com/thumbor/jUqQ5PO2pDh4Xl9UlK5O8Hiykjc=/0x0:600x523/768x768/filters:focal(300x262:301x263)/cdn.vox-cdn.com/uploads/chorus_asset/file/22536349/Sony_X950H_4K_TV_75_Inch_Side_Angle_Photo.png", "The Sony X950H is a premium 4K TV with stunning picture quality, featuring X-Motion Clarity and Dolby Vision. It's powered by Android TV, offering access to numerous streaming services. Available in Silver.", null, "65\"", null, "Android TV", "Silver", categoryRepository.findById(3L).orElse(null), null, 0.0, LocalDateTime.now(), LocalDateTime.now()));
            productRepository.save(new Product(getRandomId(), "Philips 7500 Series", "Philips", new BigDecimal("899.99"), "https://www.gotdeal.nl/wp-content/uploads/2022/12/philips51-1024x1024.png", "The Philips 7500 Series is a 4K LED TV with excellent picture quality, featuring Ambilight, HDR10+, and Dolby Vision. It runs on Android TV, offering a wide range of apps and smart features. Available in Black.", null, "55\"", null, "Android TV", "Black", categoryRepository.findById(3L).orElse(null), null, 0.0, LocalDateTime.now(), LocalDateTime.now()));
            productRepository.save(new Product(getRandomId(), "Vizio P-Series", "Vizio", new BigDecimal("999.99"), "https://www.dolby.com/globalassets/primary/p-series-primary.png", "The Vizio P-Series is a high-performance 4K TV with Quantum Color and 240Hz effective refresh rate. It's ideal for gaming and movies, featuring SmartCast for easy streaming. Available in Black.", null, "65\"", null, "SmartCast", "Black", categoryRepository.findById(3L).orElse(null), null, 0.0, LocalDateTime.now(), LocalDateTime.now()));
            productRepository.save(new Product(getRandomId(), "Philips Ambilight TV", "Philips", new BigDecimal("1299.99"), "https://img.telemart.ua/540310-690840/philips-65-65pus811812-black.png", "The Philips Ambilight TV offers an immersive viewing experience with its Ambilight technology, projecting light beyond the screen. It features a 4K UHD display and SAPHI smart TV system. Available in Black.", null, "55\"", null, "SAPHI", "Black", categoryRepository.findById(3L).orElse(null), null, 0.0, LocalDateTime.now(), LocalDateTime.now()));
            productRepository.save(new Product(getRandomId(), "Hisense U8G", "Hisense", new BigDecimal("999.99"), "https://bgr.com/wp-content/uploads/2022/10/hisense-u8h.png?w=700&h=518&crop=1", "The Hisense U8G is a high-performance 4K TV featuring Quantum Dot technology for vibrant colors and Dolby Vision HDR. It's powered by Android TV for a wide range of apps and services. Available in Black.", null, "55\"", null, "Android TV", "Black", categoryRepository.findById(3L).orElse(null), null, 0.0, LocalDateTime.now(), LocalDateTime.now()));
            productRepository.save(new Product(getRandomId(), "Samsung Crystal UHD", "Samsung", new BigDecimal("699.99"), "https://www.samline.co.il/wp-content/uploads/2021/03/TU8000UTH1_011_Front3_Black-1-795x530.png.webp", "The Samsung Crystal UHD TV offers great picture quality and vibrant colors at an affordable price. It's powered by Tizen, providing easy access to streaming services and apps. Available in Black.", null, "50\"", null, "Tizen", "Black", categoryRepository.findById(3L).orElse(null), null, 0.0, LocalDateTime.now(), LocalDateTime.now()));
            productRepository.save(new Product(getRandomId(), "LG CX OLED", "LG", new BigDecimal("1899.99"), "https://hdtvtest.co.uk/static_data/content/fee_786_587_-33e7b21f-f66c-4145-acae-9a1a69f80fae.jpg", "The LG CX OLED TV offers premium picture quality with perfect blacks and infinite contrast. It's powered by WebOS for a seamless smart TV experience, perfect for movies and gaming. Available in Black.", null, "55\"", null, "WebOS", "Black", categoryRepository.findById(3L).orElse(null), null, 0.0, LocalDateTime.now(), LocalDateTime.now()));
            productRepository.save(new Product(getRandomId(), "Sony A8H OLED", "Sony", new BigDecimal("1999.99"), "https://sonyimages.blob.core.windows.net/productr/large/KE65A8BU_0.png", "The Sony A8H OLED TV offers stunning picture quality with perfect blacks and vibrant colors. It's powered by Android TV, providing access to numerous streaming services. Available in Black.", null, "55\"", null, "Android TV", "Black", categoryRepository.findById(3L).orElse(null), null, 0.0, LocalDateTime.now(), LocalDateTime.now()));
            productRepository.save(new Product(getRandomId(), "Sony Bravia X900H", "Sony", new BigDecimal("1299.99"), "https://www.sony.ca/image/1f8b12dad8fe7f11f59c7372bf8d95cb?fmt=png-alpha&wid=900&hei=800", "The Sony Bravia X900H is a high-end 4K LED TV with stunning picture quality, featuring Full Array LED, Dolby Vision, and HDR. It runs on Android TV, offering a wide range of smart features and apps. Available in Black.", null, "65\"", null, "Android TV", "Black", categoryRepository.findById(3L).orElse(null), null, 0.0, LocalDateTime.now(), LocalDateTime.now()));
            productRepository.save(new Product(getRandomId(), "Vizio V-Series", "Vizio", new BigDecimal("399.99"), "https://www.vizio.com/content/dam/vizio/us/en/images/spring-refresh-tv/v-series/v-series-hero-media.png/_jcr_content/renditions/cq5dam.resized.rsz-desk.png", "The Vizio V-Series is a budget-friendly 4K TV offering good features, including full array backlighting and SmartCast for easy streaming. Perfect for everyday use. Available in Black.", null, "50\"", null, "SmartCast", "Black", categoryRepository.findById(3L).orElse(null), null, 0.0, LocalDateTime.now(), LocalDateTime.now()));
            productRepository.save(new Product(getRandomId(), "Philips 3-Series", "Philips", new BigDecimal("299.99"), "https://assets.gy.digital/YwMV_47uelS59mfXK3g7bq7Nc94=/600x600/s3.gy.digital%2Fgotech%2Fuploads%2Fasset%2Fdata%2F8881%2FPR-3_7906_F6_PR-3.png", "The Philips 3-Series is an entry-level 4K TV with decent features, including HDR10 and SAPHI smart TV system for a user-friendly interface. Available in Black.", null, "43\"", null, "SAPHI", "Black", categoryRepository.findById(3L).orElse(null), null, 0.0, LocalDateTime.now(), LocalDateTime.now()));
            productRepository.save(new Product(getRandomId(), "Hisense A6G", "Hisense", new BigDecimal("299.99"), "https://adebowaleemporium.com/wp-content/uploads/2022/10/img_2175-1.png", "The Hisense A6G is a budget-friendly 4K TV offering good performance, featuring HDR and Android TV for a wide range of apps. Perfect for everyday viewing. Available in Black.", null, "43\"", null, "Android TV", "Black", categoryRepository.findById(3L).orElse(null), null, 0.0, LocalDateTime.now(), LocalDateTime.now()));
            productRepository.save(new Product(getRandomId(), "Samsung Serif TV", "Samsung", new BigDecimal("1499.99"), "https://images.samsung.com/is/image/samsung/p6pim/au/qa65qn85dbwxxy/gallery/au-qled-qn85d-qa65qn85dbwxxy-540642107?$650_519_PNG$", "The Samsung Serif TV is a stylish TV with a unique design that stands out in any room. It offers a QLED 4K display and Tizen smart TV system. Available in White.", null, "55\"", null, "Tizen", "White", categoryRepository.findById(3L).orElse(null), null, 0.0, LocalDateTime.now(), LocalDateTime.now()));
            productRepository.save(new Product(getRandomId(), "LG GX OLED", "LG", new BigDecimal("1999.99"), "https://www.pricerunner.com/product/640x640/3000264189/LG-OLED55GX.jpg?ph=true", "The LG GX OLED TV features a gallery design, making it a beautiful addition to any living space. It offers perfect blacks and vivid colors, powered by WebOS for seamless streaming. Available in Black.", null, "65\"", null, "WebOS", "Black", categoryRepository.findById(3L).orElse(null), null, 0.0, LocalDateTime.now(), LocalDateTime.now()));
            productRepository.save(new Product(getRandomId(), "Sony X900H", "Sony", new BigDecimal("1199.99"), "https://cdn.cs.1worldsync.com/syndication/mediaserverredirect/0af32a4e26ab4a4fa89a76fdcd9383c7/original.png", "The Sony X900H is a mid-range 4K TV offering good features, including full array local dimming and Android TV for a wide range of streaming options. Available in Black.", null, "55\"", null, "Android TV", "Black", categoryRepository.findById(3L).orElse(null), null, 0.0, LocalDateTime.now(), LocalDateTime.now()));

            // Laptop Products
            productRepository.save(new Product(getRandomId(), "Dell XPS 13", "Dell", new BigDecimal("999.99"), "https://i.dell.com/is/image/DellContent/content/dam/ss2/product-images/dell-client-products/notebooks/xps-notebooks/13-9340/pdp/laptop-xps-13-9340-pdp-display-sl.psd?fmt=png-alpha&wid=1080&hei=825", "The Dell XPS 13 is an ultra-thin and powerful laptop, featuring a 13.4-inch display and 256GB SSD storage. It's designed for professionals and students who need performance in a compact form. Available in Silver.", "256GB SSD", "13.4\"", "52Wh", "Windows 10", "Silver", categoryRepository.findById(1L).orElse(null), null, 0.0, LocalDateTime.now(), LocalDateTime.now()));
            productRepository.save(new Product(getRandomId(), "MacBook Air", "Apple", new BigDecimal("1099.99"), "https://www.dimprice.co.uk/image/cache/png/apple-macbook-air-2020/Space%20Grey/apple-macbook-air-2020-space-grey-01-800x800.png", "The MacBook Air is a lightweight and powerful MacBook, perfect for on-the-go use. It features a 13.3-inch Retina display, 256GB SSD storage, and the latest macOS for seamless performance. Available in Space Gray.", "256GB SSD", "13.3\"", "49.9Wh", "macOS", "Space Gray", categoryRepository.findById(1L).orElse(null), null, 0.0, LocalDateTime.now(), LocalDateTime.now()));
            productRepository.save(new Product(getRandomId(), "HP Spectre x360", "HP", new BigDecimal("1199.99"), "https://www.paklap.pk/media/catalog/product/cache/2cc443e44e97595ea39006016c876eaa/d/d/ddddddddd_2.png", "The HP Spectre x360 is a versatile 2-in-1 laptop, offering a 13.3-inch touch display and 512GB SSD storage. It's ideal for both work and play, with the flexibility to use as a laptop or tablet. Available in Dark Ash Silver.", "512GB SSD", "13.3\"", "60Wh", "Windows 10", "Dark Ash Silver", categoryRepository.findById(1L).orElse(null), null, 0.0, LocalDateTime.now(), LocalDateTime.now()));
            productRepository.save(new Product(getRandomId(), "Lenovo ThinkPad X1 Carbon", "Lenovo", new BigDecimal("1299.99"), "https://d3m9l0v76dty0.cloudfront.net/system/photos/9737523/large/e7e1fd1170d5249281607ccd9f4453c7.png", "The Lenovo ThinkPad X1 Carbon is a durable and powerful business laptop, featuring a 14-inch display and 512GB SSD storage. It's built for professionals who need reliability and performance on the go. Available in Black.", "512GB SSD", "14\"", "51Wh", "Windows 10", "Black", categoryRepository.findById(1L).orElse(null), null, 0.0, LocalDateTime.now(), LocalDateTime.now()));
            productRepository.save(new Product(getRandomId(), "Microsoft Surface Laptop 3", "Microsoft", new BigDecimal("1199.99"), "https://res-5.cloudinary.com/grover/image/upload/e_trim/c_limit,f_auto,fl_png8.lossy,h_500,q_auto,w_500/v1570789384/jqivkr81dzjcehgunj3j.png", "The Microsoft Surface Laptop 3 is a stylish and powerful laptop, offering a 13.5-inch display and 256GB SSD storage. It's designed for productivity and creativity, with a sleek and elegant design. Available in Platinum.", "256GB SSD", "13.5\"", "45.8Wh", "Windows 10", "Platinum", categoryRepository.findById(1L).orElse(null), null, 0.0, LocalDateTime.now(), LocalDateTime.now()));
            productRepository.save(new Product(getRandomId(), "Acer Swift 3", "Acer", new BigDecimal("699.99"), "https://ptechktm.com/pub/media/catalog/product/cache/c5e7b9476bc5c467d5a18a620cce69d8/u/n/untitled_design_64_.png", "The Acer Swift 3 is an affordable and lightweight laptop, featuring a 14-inch display and 256GB SSD storage. It's perfect for students and budget-conscious users who need a reliable and portable device. Available in Silver.", "256GB SSD", "14\"", "48Wh", "Windows 10", "Silver", categoryRepository.findById(1L).orElse(null), null, 0.0, LocalDateTime.now(), LocalDateTime.now()));
            productRepository.save(new Product(getRandomId(), "Razer Blade 15", "Razer", new BigDecimal("1599.99"), "https://pselectronic.com.au/wp-content/uploads/2021/11/RZ09-0287-1.png", "The Razer Blade 15 is a high-performance gaming laptop, featuring a 15.6-inch display and 512GB SSD storage. It's designed for gamers who need top-tier performance and sleek design. Available in Black.", "512GB SSD", "15.6\"", "80Wh", "Windows 10", "Black", categoryRepository.findById(1L).orElse(null), null, 0.0, LocalDateTime.now(), LocalDateTime.now()));
            productRepository.save(new Product(getRandomId(), "Asus ROG Zephyrus G14", "Asus", new BigDecimal("1299.99"), "https://www.hidevolution.com/media/catalog/product/cache/1/image/9df78eab33525d08d6e5fb8d27136e95/2/_/2_11_4.png", "The Asus ROG Zephyrus G14 is a compact gaming laptop with great performance, featuring a 14-inch display and 1TB SSD storage. It's perfect for gamers who need power in a portable package. Available in White.", "1TB SSD", "14\"", "76Wh", "Windows 10", "White", categoryRepository.findById(1L).orElse(null), null, 0.0, LocalDateTime.now(), LocalDateTime.now()));
            productRepository.save(new Product(getRandomId(), "HP Envy x360", "HP", new BigDecimal("899.99"), "https://media-ik.croma.com/prod/https://media.croma.com/image/upload/v1703081254/Croma%20Assets/Computers%20Peripherals/Laptop/Images/275036_0_tqqxbq.png?tr=w-600", "The HP Envy x360 is a convertible laptop with good performance, featuring a 15.6-inch touch display and 512GB SSD storage. It's versatile for both work and entertainment, allowing use as a laptop or tablet. Available in Nightfall Black.", "512GB SSD", "15.6\"", "51Wh", "Windows 10", "Black", categoryRepository.findById(1L).orElse(null), null, 0.0, LocalDateTime.now(), LocalDateTime.now()));
            productRepository.save(new Product(getRandomId(), "Dell Inspiron 15", "Dell", new BigDecimal("599.99"), "https://img-prd-pim.poorvika.com/cdn-cgi/image/width=500,height=500,quality=75/product/dell-inspiron-3511-intel-core-i5-11th-gen-windows-11-home-laptop-d560652win9s-platinum-silver-8gb-ram-512gb-ssd-right-view.png", "The Dell Inspiron 15 is an affordable laptop with good features, offering a 15.6-inch display and 256GB SSD storage. It's ideal for everyday use, providing reliability and performance. Available in Platinum Silver.", "256GB SSD", "15.6\"", "42Wh", "Windows 10", "Platinum Silver", categoryRepository.findById(1L).orElse(null), null, 0.0, LocalDateTime.now(), LocalDateTime.now()));
            productRepository.save(new Product(getRandomId(), "Apple MacBook Pro 16", "Apple", new BigDecimal("2399.99"), "https://www.playforce.com.sg/cdn/shop/files/1_27f976b1-bfe1-43ca-8d62-2ecbcdc0afb3_large.png?v=1706685202", "The Apple MacBook Pro 16 is a high-end MacBook with a large display, featuring a 16-inch Retina display and 512GB SSD storage. It's perfect for professionals who need power and performance. Available in Space Gray.", "512GB SSD", "16\"", "100Wh", "macOS", "Space Gray", categoryRepository.findById(1L).orElse(null), null, 0.0, LocalDateTime.now(), LocalDateTime.now()));
            productRepository.save(new Product(getRandomId(), "Lenovo Yoga C940", "Lenovo", new BigDecimal("1399.99"), "https://i0.wp.com/www.bovic.co.ke/wp-content/uploads/2021/09/lenovo-laptop-yoga-c940-www.bovic_.co_.ke_.png?fit=600%2C600&ssl=1", "The Lenovo Yoga C940 is a versatile 2-in-1 laptop, featuring a 14-inch touch display and 1TB SSD storage. It's designed for flexibility, allowing use as a laptop or tablet. Available in Iron Gray.", "1TB SSD", "14\"", "60Wh", "Windows 10", "Iron Gray", categoryRepository.findById(1L).orElse(null), null, 0.0, LocalDateTime.now(), LocalDateTime.now()));
            productRepository.save(new Product(getRandomId(), "Microsoft Surface Pro 7", "Microsoft", new BigDecimal("899.99"), "https://www.stockmustgo.co.uk/cdn/shop/files/RE4tjV5_b5a0fabf-4167-4312-8f20-22c284d17866.png?v=1714379619&width=850", "The Microsoft Surface Pro 7 is a 2-in-1 laptop with a detachable keyboard, featuring a 12.3-inch touch display and 128GB SSD storage. It's perfect for on-the-go productivity. Available in Platinum.", "128GB SSD", "12.3\"", "43.2Wh", "Windows 10", "Platinum", categoryRepository.findById(1L).orElse(null), null, 0.0, LocalDateTime.now(), LocalDateTime.now()));
            productRepository.save(new Product(getRandomId(), "Asus ZenBook 14", "Asus", new BigDecimal("899.99"), "https://redington-prod-data-product-images.s3.ap-south-1.amazonaws.com/TSCPNB1104/TSCPNB1104_1.png", "The Asus ZenBook 14 is a thin and light laptop with good performance, featuring a 14-inch display and 512GB SSD storage. It's designed for professionals and students who need portability. Available in Pine Grey.", "512GB SSD", "14\"", "67Wh", "Windows 10", "Pine Grey", categoryRepository.findById(1L).orElse(null), null, 0.0, LocalDateTime.now(), LocalDateTime.now()));
            productRepository.save(new Product(getRandomId(), "HP Pavilion 15", "HP", new BigDecimal("699.99"), "https://www.hpshop.co.za/media/catalog/product/cache/f17faa3ce6712b832cc24c3d69b158ff/1/_/1.product-800x600-center_facing-c08387016_1.png", "The HP Pavilion 15 is an affordable laptop with good features, featuring a 15.6-inch display and 512GB SSD storage. It's perfect for everyday use, providing reliability and performance. Available in Natural Silver.", "512GB SSD", "15.6\"", "41Wh", "Windows 10", "Silver", categoryRepository.findById(1L).orElse(null), null, 0.0, LocalDateTime.now(), LocalDateTime.now()));
            productRepository.save(new Product(getRandomId(), "Dell G5 15", "Dell", new BigDecimal("899.99"), "https://admin.itti.com.np/storage/product/dell-g5-5515-3050-gaming-laptop-price-nepal/thumb/fd188a9f-9d8e-404e-b357-a441a4747d5c.png", "The Dell G5 15 is a gaming laptop with good performance, featuring a 15.6-inch display and 256GB SSD storage. It's designed for gamers who need power and affordability. Available in Black.", "256GB SSD", "15.6\"", "51Wh", "Windows 10", "Black", categoryRepository.findById(1L).orElse(null), null, 0.0, LocalDateTime.now(), LocalDateTime.now()));
            productRepository.save(new Product(getRandomId(), "Apple MacBook Pro 13", "Apple", new BigDecimal("1299.99"), "https://www.dimprice.co.uk/image/cache/catalog/Apple/apple-macbook-pro-2022-silver-2-800x800.png", "The Apple MacBook Pro 13 is a compact and powerful MacBook, featuring a 13.3-inch Retina display and 256GB SSD storage. It's perfect for professionals who need performance on the go. Available in Silver.", "256GB SSD", "13.3\"", "58.2Wh", "macOS", "Silver", categoryRepository.findById(1L).orElse(null), null, 0.0, LocalDateTime.now(), LocalDateTime.now()));
            productRepository.save(new Product(getRandomId(), "Acer Predator Helios 300", "Acer", new BigDecimal("1199.99"), "https://itechstore.com.np/_ipx/w_1536&f_png/img/product/2493f5fc-8622-4d17-b3cb-93b0a9791261/acer-predator-helios-300-2022-3.png", "The Acer Predator Helios 300 is a high-performance gaming laptop, featuring a 15.6-inch display and 512GB SSD storage. It's designed for gamers who need power and portability. Available in Black.", "512GB SSD", "15.6\"", "59Wh", "Windows 10", "Black", categoryRepository.findById(1L).orElse(null), null, 0.0, LocalDateTime.now(), LocalDateTime.now()));
            productRepository.save(new Product(getRandomId(), "Asus TUF Gaming A15", "Asus", new BigDecimal("999.99"), "https://www.asus.com/media/global/gallery/c0fgpdhpjyf8ajft_setting_xxx_0_90_end_800.png", "The Asus TUF Gaming A15 is a durable gaming laptop with good performance, featuring a 15.6-inch display and 512GB SSD storage. It's built for gamers who need reliability. Available in Bonfire Black.", "512GB SSD", "15.6\"", "90Wh", "Windows 10", "Black", categoryRepository.findById(1L).orElse(null), null, 0.0, LocalDateTime.now(), LocalDateTime.now()));
            productRepository.save(new Product(getRandomId(), "HP Omen 15", "HP", new BigDecimal("1299.99"), "https://media-ik.croma.com/prod/https://media.croma.com/image/upload/v1701192955/Croma%20Assets/Computers%20Peripherals/Laptop/Images/275632_0_gvph6k.png?tr=w-600", "The HP Omen 15 is a powerful gaming laptop with good features, featuring a 15.6-inch display and 1TB SSD storage. It's designed for gamers who need performance and storage. Available in Mica Silver.", "1TB SSD", "15.6\"", "70.9Wh", "Windows 10", "Mica Silver", categoryRepository.findById(1L).orElse(null), null, 0.0, LocalDateTime.now(), LocalDateTime.now()));
            productRepository.save(new Product(getRandomId(), "Dell Latitude 7420", "Dell", new BigDecimal("1399.99"), "https://www.carltontechnologies.com/wp-content/uploads/2021/04/Dell-Latitude-7420-14-Inch-Laptop.png", "The Dell Latitude 7420 is a business laptop with good performance, featuring a 14-inch display and 512GB SSD storage. It's perfect for professionals who need reliability and power. Available in Carbon Fiber.", "512GB SSD", "14\"", "42Wh", "Windows 10", "Carbon Fiber", categoryRepository.findById(1L).orElse(null), null, 0.0, LocalDateTime.now(), LocalDateTime.now()));
            productRepository.save(new Product(getRandomId(), "Lenovo Legion 5", "Lenovo", new BigDecimal("1099.99"), "https://www.stockmustgo.co.uk/cdn/shop/products/largeimgB45793527-removebg-preview_1024x.png?v=1660149815", "The Lenovo Legion 5 is a gaming laptop with good performance, featuring a 15.6-inch display and 512GB SSD storage. It's designed for gamers who need power and affordability. Available in Phantom Blue.", "512GB SSD", "15.6\"", "60Wh", "Windows 10", "Phantom Blue", categoryRepository.findById(1L).orElse(null), null, 0.0, LocalDateTime.now(), LocalDateTime.now()));
            productRepository.save(new Product(getRandomId(), "Asus VivoBook S15", "Asus", new BigDecimal("699.99"), "https://www.pc-online.co.il/skpic/28438-1-1230d.png", "The Asus VivoBook S15 is an affordable laptop with good features, featuring a 15.6-inch display and 256GB SSD storage. It's perfect for everyday use, providing reliability and performance. Available in Dreamy White.", "256GB SSD", "15.6\"", "42Wh", "Windows 10", "White", categoryRepository.findById(1L).orElse(null), null, 0.0, LocalDateTime.now(), LocalDateTime.now()));
            productRepository.save(new Product(getRandomId(), "Acer Nitro 5", "Acer", new BigDecimal("899.99"), "https://www.gigahertz.com.ph/cdn/shop/products/Nitro-5-12th-Gen-Leftpng_1024x.png?v=1709715870", "The Acer Nitro 5 is a gaming laptop with good performance, featuring a 15.6-inch display and 256GB SSD storage. It's designed for gamers who need power and affordability. Available in Obsidian Black.", "256GB SSD", "15.6\"", "55Wh", "Windows 10", "Black", categoryRepository.findById(1L).orElse(null), null, 0.0, LocalDateTime.now(), LocalDateTime.now()));
            productRepository.save(new Product(getRandomId(), "HP Elite Dragonfly", "HP", new BigDecimal("1499.99"), "https://millenniuminfosys.com/wp-content/uploads/2024/03/HP-Elite-Dragonfly-13.5-inch-G3-Notebook-Computer.png", "The HP Elite Dragonfly is a business laptop with good features, featuring a 13.3-inch display and 512GB SSD storage. It's perfect for professionals who need portability and performance. Available in Dragonfly Blue.", "512GB SSD", "13.3\"", "38Wh", "Windows 10", "Blue", categoryRepository.findById(1L).orElse(null), null, 0.0, LocalDateTime.now(), LocalDateTime.now()));
            productRepository.save(new Product(getRandomId(), "Microsoft Surface Book 3", "Microsoft", new BigDecimal("2299.99"), "https://www.stockmustgo.co.uk/cdn/shop/products/microsoft-surface-book-3-laptop-intel-core-i7-processor-32gb-ram-512gb-ssd-15-pixelsense-display-platinum-4_6611e163-935e-46b6-b193-20d34b579539_1024x.png?v=1669394754", "The Microsoft Surface Book 3 is a high-performance 2-in-1 laptop, featuring a 15-inch touch display and 512GB SSD storage. It's designed for professionals who need flexibility and power. Available in Platinum.", "512GB SSD", "15\"", "70Wh", "Windows 10", "Platinum", categoryRepository.findById(1L).orElse(null), null, 0.0, LocalDateTime.now(), LocalDateTime.now()));

            // Headphone Products
            productRepository.save(new Product(getRandomId(), "Sony WH-1000XM4", "Sony", new BigDecimal("349.99"), "https://thumbor.arvutitark.ee/rOuZfmiBhrcS3eIdwSdp8x5JLRo=/trim/fit-in/800x800/filters:format(webp)/https%3A%2F%2Fstorage.googleapis.com%2Farvutitark-prod%2Fpublic%2Fmedia-hub-cms%2F2023%2F03%2F357574%2FWH1000XM4B.png", "The Sony WH-1000XM4 are industry-leading noise-canceling headphones, offering superior sound quality and long battery life. Perfect for immersive listening experiences. Available in Black.", null, null, "30 hours", null, "Black", categoryRepository.findById(4L).orElse(null), null, 0.0, LocalDateTime.now(), LocalDateTime.now()));
            productRepository.save(new Product(getRandomId(), "Bose QuietComfort 35 II", "Bose", new BigDecimal("299.99"), "https://tele2.ee/api/webp?src=https://tele2.ee/media/catalog/product/cache/5e8ba96e32502a294eac11fbf6d5ef42/b/o/bose_qcii_silver.png", "The Bose QuietComfort 35 II are comfortable and great-sounding headphones, featuring world-class noise cancellation and a long battery life. Ideal for travel and daily use. Available in Silver.", null, null, "20 hours", null, "Silver", categoryRepository.findById(4L).orElse(null), null, 0.0, LocalDateTime.now(), LocalDateTime.now()));
            productRepository.save(new Product(getRandomId(), "Apple AirPods Pro", "Apple", new BigDecimal("249.99"), "https://www.att.com/scmsassets/global/accessories/audio/apple/apple-airpods-pro-2nd-generation-with-magsafe-charging-case-usb-c/defaultimage/4417s-white-hero-zoom.png", "The Apple AirPods Pro are noise-canceling true wireless earbuds, offering a comfortable fit and excellent sound quality. Perfect for music lovers and daily use. Available in White.", null, null, "4.5 hours", null, "White", categoryRepository.findById(4L).orElse(null), null, 0.0, LocalDateTime.now(), LocalDateTime.now()));
            productRepository.save(new Product(getRandomId(), "Sennheiser HD 450BT", "Sennheiser", new BigDecimal("199.99"), "https://files.katerelos.gr/cdn/df/mediasupply/2020/02/522475_00.png", "The Sennheiser HD 450BT offer great sound quality with noise canceling, featuring a long battery life and comfortable design. Ideal for daily listening. Available in Black.", null, null, "30 hours", null, "Black", categoryRepository.findById(4L).orElse(null), null, 0.0, LocalDateTime.now(), LocalDateTime.now()));
            productRepository.save(new Product(getRandomId(), "Jabra Elite 85h", "Jabra", new BigDecimal("299.99"), "https://www.jabra.com/en-ca/-/media/Images/Products/Jabra-Elite-85h/Layout/KSP2_SmartANC/anc_headphones.png?la=en-CA&hash=FB0DA655A0BD3984A6C4F426EC80747488B35E5F", "The Jabra Elite 85h are smart active noise-canceling headphones, offering excellent sound quality and a long battery life. Perfect for commuters and frequent travelers. Available in Titanium Black.", null, null, "36 hours", null, "Black", categoryRepository.findById(4L).orElse(null), null, 0.0, LocalDateTime.now(), LocalDateTime.now()));
            productRepository.save(new Product(getRandomId(), "Beats Solo Pro", "Beats", new BigDecimal("299.99"), "https://www.att.com/scmsassets/global/accessories/headphones/beats/beats-solo-pro-wireless-noise-cancelling-headphones/defaultimage/White-hero-zoom.png", "The Beats Solo Pro are noise-canceling on-ear headphones, providing a powerful listening experience with a long battery life. Ideal for music enthusiasts. Available in Ivory.", null, null, "22 hours", null, "Ivory", categoryRepository.findById(4L).orElse(null), null, 0.0, LocalDateTime.now(), LocalDateTime.now()));
            productRepository.save(new Product(getRandomId(), "Sony WF-1000XM3", "Sony", new BigDecimal("229.99"), "https://dv9dhd03d71d4.cloudfront.net/eyJidWNrZXQiOiJwcm9kLXd3dy1hc3NldHMtcGVyZmVjdHJlYyIsImtleSI6ImltYWdlcy9wcm9kdWN0cy9oZWFkcGhvbmVzL0lNR19Tb255X1dGMTAwMFhNMy5wbmciLCJlZGl0cyI6eyJyZXNpemUiOnsid2lkdGgiOjYwMCwiZml0IjoiY292ZXIifX19", "The Sony WF-1000XM3 are noise-canceling true wireless earbuds, offering superior sound quality and a long battery life. Perfect for daily use. Available in Black.", null, null, "6 hours", null, "Black", categoryRepository.findById(4L).orElse(null), null, 0.0, LocalDateTime.now(), LocalDateTime.now()));
            productRepository.save(new Product(getRandomId(), "Bose SoundSport Free", "Bose", new BigDecimal("199.99"), "https://assets.bosecreative.com/m/52a2d28c291aa0bb/webimage-SSW_CC_011_CMYK.png", "The Bose SoundSport Free are true wireless earbuds for sports, offering a secure fit and excellent sound quality. Ideal for workouts and active lifestyles. Available in Blue.", null, null, "5 hours", null, "Blue", categoryRepository.findById(4L).orElse(null), null, 0.0, LocalDateTime.now(), LocalDateTime.now()));
            productRepository.save(new Product(getRandomId(), "Apple AirPods Max", "Apple", new BigDecimal("549.99"), "https://help.apple.com/assets/65F1C66A94AC154A7D0E2E94/65F1C66D12C94DFB570CD201/en_US/be407fad48c9ccafcd87007eb6645d61.png", "The Apple AirPods Max are high-end over-ear headphones, offering exceptional sound quality and active noise cancellation. Perfect for audiophiles. Available in Silver.", null, null, "20 hours", null, "Silver", categoryRepository.findById(4L).orElse(null), null, 0.0, LocalDateTime.now(), LocalDateTime.now()));
            productRepository.save(new Product(getRandomId(), "Sennheiser Momentum 3", "Sennheiser", new BigDecimal("399.99"), "https://cdn.mos.cms.futurecdn.net/hk25vbTebbmBo2o738CrFP-320-80.png", "The Sennheiser Momentum 3 are high-quality over-ear headphones, featuring noise cancellation and excellent sound performance. Ideal for premium listening experiences. Available in Black.", null, null, "17 hours", null, "Black", categoryRepository.findById(4L).orElse(null), null, 0.0, LocalDateTime.now(), LocalDateTime.now()));
            productRepository.save(new Product(getRandomId(), "Jabra Elite Active 75t", "Jabra", new BigDecimal("199.99"), "https://cdn.pim.ac-systems.com/6/67208/images/192619-large.png", "The Jabra Elite Active 75t are true wireless earbuds for sports, offering a secure fit and great sound quality with a long battery life. Perfect for active lifestyles. Available in Navy.", null, null, "7.5 hours", null, "Navy", categoryRepository.findById(4L).orElse(null), null, 0.0, LocalDateTime.now(), LocalDateTime.now()));
            productRepository.save(new Product(getRandomId(), "Beats Studio3", "Beats", new BigDecimal("349.99"), "https://www.macansys.co.uk/wp-content/uploads/imported/2/BEATS-Studio-3-Wireless-Bluetooth-Noise-Cancelling-Headphones-Midnight-Black-New-175670077112-7.png", "The Beats Studio3 are over-ear headphones with noise canceling, providing a premium listening experience and a long battery life. Ideal for music lovers. Available in Matte Black.", null, null, "22 hours", null, "Black", categoryRepository.findById(4L).orElse(null), null, 0.0, LocalDateTime.now(), LocalDateTime.now()));
            productRepository.save(new Product(getRandomId(), "Sony WH-H910N", "Sony", new BigDecimal("299.99"), "https://res-3.cloudinary.com/grover/image/upload/e_trim/c_limit,f_auto,fl_png8.lossy,h_500,q_auto,w_500/v1571065065/yna8bd1tic2m7crzwtzh.png", "The Sony WH-H910N are noise-canceling on-ear headphones, offering excellent sound quality and a long battery life. Perfect for daily use. Available in Green.", null, null, "35 hours", null, "Green", categoryRepository.findById(4L).orElse(null), null, 0.0, LocalDateTime.now(), LocalDateTime.now()));
            productRepository.save(new Product(getRandomId(), "Bose Noise Cancelling Headphones 700", "Bose", new BigDecimal("379.99"), "https://assets.bosecreative.com/m/438150a34e7561b0/webimage-HP700_Black_002_RGB.png", "The Bose Noise Cancelling Headphones 700 are high-end noise-canceling headphones, offering exceptional sound quality and a long battery life. Perfect for professionals and travelers. Available in Black.", null, null, "20 hours", null, "Black", categoryRepository.findById(4L).orElse(null), null, 0.0, LocalDateTime.now(), LocalDateTime.now()));
            productRepository.save(new Product(getRandomId(), "Apple Beats Flex", "Apple", new BigDecimal("49.99"), "https://join-banana.com/cdn/shop/products/fee_786_587_png_ac24229a-78c4-4539-ab7c-d8a3bd4a0772.png?crop=center&height=430&v=1690281144&width=310", "The Apple Beats Flex are affordable wireless earphones, offering good sound quality and a comfortable fit with a long battery life. Perfect for everyday use. Available in Yuzu Yellow.", null, null, "12 hours", null, "Yellow", categoryRepository.findById(4L).orElse(null), null, 0.0, LocalDateTime.now(), LocalDateTime.now()));
            productRepository.save(new Product(getRandomId(), "Sennheiser PXC 550-II", "Sennheiser", new BigDecimal("349.99"), "https://tryitfirst.in/pub/media/catalog/product/cache/030716fc62035027b622eeef186d3d67/e/l/elite85h-black-7.jpg", "The Sennheiser PXC 550-II are high-quality over-ear headphones with noise canceling, offering excellent sound and a long battery life. Ideal for travel and daily use. Available in Black.", null, null, "30 hours", null, "Black", categoryRepository.findById(4L).orElse(null), null, 0.0, LocalDateTime.now(), LocalDateTime.now()));
            productRepository.save(new Product(getRandomId(), "Jabra Move Style Edition", "Jabra", new BigDecimal("99.99"), "https://img.productz.com/2311382/jabra-elite-45h-18-preview.png", "The Jabra Move Style Edition are affordable wireless on-ear headphones, offering good sound quality and a comfortable fit with a long battery life. Perfect for everyday use. Available in Gold Beige.", null, null, "14 hours", null, "Gold Beige", categoryRepository.findById(4L).orElse(null), null, 0.0, LocalDateTime.now(), LocalDateTime.now()));
            productRepository.save(new Product(getRandomId(), "Beats Powerbeats Pro", "Beats", new BigDecimal("249.99"), "https://cdn.arstechnica.net/wp-content/uploads/2019/04/Powerbeats-Pro-navy.png", "The Beats Powerbeats Pro are high-performance true wireless earphones, offering great sound quality and a secure fit with a long battery life. Perfect for workouts and active lifestyles. Available in Navy.", null, null, "9 hours", null, "Navy", categoryRepository.findById(4L).orElse(null), null, 0.0, LocalDateTime.now(), LocalDateTime.now()));
            productRepository.save(new Product(getRandomId(), "Sony WH-CH710N", "Sony", new BigDecimal("199.99"), "https://janado.de/cdn/shop/products/51JnfYw9-tL--1.png?v=1693485449", "The Sony WH-CH710N are affordable noise-canceling headphones, offering good sound quality and a long battery life. Ideal for budget-conscious users. Available in Black.", null, null, "35 hours", null, "Black", categoryRepository.findById(4L).orElse(null), null, 0.0, LocalDateTime.now(), LocalDateTime.now()));
            productRepository.save(new Product(getRandomId(), "Bose Sport Earbuds", "Bose", new BigDecimal("179.99"), "https://assets.bosecreative.com/m/2da5e1a1849620a6/webimage-EB500_GlacierWhite_Case_001_RGB.png", "The Bose Sport Earbuds are true wireless earbuds for sports, offering a secure fit and excellent sound quality with a long battery life. Perfect for active lifestyles. Available in Glacier White.", null, null, "5 hours", null, "White", categoryRepository.findById(4L).orElse(null), null, 0.0, LocalDateTime.now(), LocalDateTime.now()));
            productRepository.save(new Product(getRandomId(), "Apple AirPods (2nd Generation)", "Apple", new BigDecimal("159.99"), "https://d3n91k3iwhucwl.cloudfront.net/media/aipodswithchargingcase.png", "The Apple AirPods (2nd Generation) are true wireless earphones with good sound quality and a comfortable fit, offering a long battery life. Perfect for everyday use. Available in White.", null, null, "5 hours", null, "White", categoryRepository.findById(4L).orElse(null), null, 0.0, LocalDateTime.now(), LocalDateTime.now()));
            productRepository.save(new Product(getRandomId(), "Sennheiser HD 4.50 BTNC", "Sennheiser", new BigDecimal("199.99"), "https://tryitfirst.in/pub/media/catalog/product/cache/030716fc62035027b622eeef186d3d67/e/l/elite85h-black-7.jpg", "The Sennheiser HD 4.50 BTNC are affordable noise-canceling headphones, offering good sound quality and a long battery life. Ideal for budget-conscious users. Available in Black.", null, null, "19 hours", null, "Black", categoryRepository.findById(4L).orElse(null), null, 0.0, LocalDateTime.now(), LocalDateTime.now()));
            productRepository.save(new Product(getRandomId(), "Jabra Elite 65t", "Jabra", new BigDecimal("149.99"), "https://cdn.pim.ac-systems.com/6/67208/images/192619-large.png", "The Jabra Elite 65t are true wireless earbuds with good sound quality and a secure fit, offering a long battery life. Perfect for everyday use. Available in Titanium Black.", null, null, "5 hours", null, "Black", categoryRepository.findById(4L).orElse(null), null, 0.0, LocalDateTime.now(), LocalDateTime.now()));
            productRepository.save(new Product(getRandomId(), "Beats EP", "Beats", new BigDecimal("99.99"), "https://img.tw.my-best.com/product_images/c7302045422a9d51818a73da3f2dea0f.png?ixlib=rails-4.3.1&q=70&lossless=0&w=800&h=800&fit=clip&s=274b5eb6a9a3b2ce1c4b2ea6cc141c80", "The Beats EP are affordable on-ear headphones, offering good sound quality and a comfortable fit with a long battery life. Perfect for everyday use. Available in Red.", null, null, "20 hours", null, "Red", categoryRepository.findById(4L).orElse(null), null, 0.0, LocalDateTime.now(), LocalDateTime.now()));
            productRepository.save(new Product(getRandomId(), "Sony WI-1000X", "Sony", new BigDecimal("299.99"), "https://res-3.cloudinary.com/grover/image/upload/v1700487981/rruwm5abkbwwragshmki.png", "The Sony WI-1000X are high-quality in-ear noise-canceling earphones, offering excellent sound quality and a comfortable fit with a long battery life. Perfect for daily use. Available in Gold.", null, null, "10 hours", null, "Gold", categoryRepository.findById(4L).orElse(null), null, 0.0, LocalDateTime.now(), LocalDateTime.now()));


        }
    }

    /**
     * Generates a random ID for the products.
     */
    private long getRandomId() {
        return ThreadLocalRandom.current().nextLong(1, 10001);
    }
}

